Check for valid service override endpoint type on create and update
openstack-k8s-operators/barbican-operator pull request #115
Opened 2024-05-08 09:40 UTC by stuggi

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505

2024-05-08 09:40 UTC, stuggi commented
/hold until after freeze

2024-05-08 12:32 UTC, d34dh0r53 approved these changes
LGTM

2024-05-08 12:40 UTC, d34dh0r53 requested changes
It looks like the `ValidateRoutedOverrides` function is missing.

2024-05-23 08:05 UTC, xek approved these changes
LGTM

2024-05-23 08:10 UTC, merged