Add missing RBAC config
openstack-k8s-operators/barbican-operator pull request #44
Opened 2023-11-06 21:32 UTC by dmendiza

This patch adds the missing RBAC config for BarbicanWorker and BarbicanKeystoneListnere that is causing the controller to get stuck in a crash loop.

2023-11-07 09:06 UTC, xek requested changes
I think these files are generated with make manifests. Are the proper kubebuilder annotations already there? If not, the pull request should update both places, like in this commit: https://github.com/openstack-k8s-operators/keystone-operator/commit/e6927b6989cfb40c65d5d82551620dabd38cb571

2023-11-08 17:33 UTC, dmendiza commented
Thanks for the review, @xek .  I had to do a bit of digging around in the operator sdk and kubebuilder docs to understand the annotations.  IIUC, the annotations are used by `make manifests` to generate the role.yaml file.  I added all the missing annotations to the Barbican controller and then updated the role.yaml file to use the one generated by the makefile.  The other files are generated by the openstack-sdk tool when a new api is added, and I think they were left out by mistake in the patch that implemented BarbicanKeystoneListener.

2023-11-08 17:53 UTC, vakwetu approved these changes
LGTM

2023-11-09 08:58 UTC, xek approved these changes

2023-11-09 08:58 UTC, merged